FROM node:12

# Read port from argument
ARG PORT=8080

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Build Angular
RUN npm run build

# Map port
EXPOSE ${PORT}

# Add environment variable
ENV DOCKER=true
ENV PORT=${PORT}

# Start server
CMD [ "node", "server.js" ]
