version: "3"
services:
  app:
    container_name: to-to-list
    restart: always
    build: .
    ports:
      - "8088:8088"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
