version: "3"
services:
  server:
    image: paranerd/to-do-list
    container_name: to-do-list
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - /path/to/config:/app/config
    ports:
      - 10111:8080
  mongo:
    container_name: to-do-list-db
    restart: unless-stopped
    image: mongo:4.4.8
    volumes:
      - to-do-list-data:/data/db

volumes:
  to-do-list-data:
